### ISSUE TITLE
ValueError: Unsupported type: _ForwardRef('DashboardBase'). Register a structure hook for it.

### ISSUE THREAD

**Issue by umairda** [looker-open-source/looker_deployer#41] opened 2020-11-20 04:31 UTC
I'm trying to export from my prod environment as follows: 
```
ldeploy content export --env prod --folders 1 --local-target .
```

And I'm getting the following error:
```
ValueError: Unsupported type: _ForwardRef('DashboardBase'). Register a structure hook for it.
```

Call Stack:
```
{"levelname": "INFO", "module": "deploy_content_export", "funcName": "main", "message": "Exporting content", "env": "prod", "folders": ["1"], "local_target": ".", "timestamp": "2020-11-20T04:26:25.896895Z"}
Traceback (most recent call last):
  File "/Users/umair/.pyenv/versions/3.6.0/bin/ldeploy", line 8, in <module>
    sys.exit(main())
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_deployer/cli.py", line 25, in main
    args.func(args)
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_deployer/commands/deploy_content_export.py", line 92, in main
    send_export(args.folders, args.local_target, args.env, args.ini, sdk, args.debug)
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_deployer/commands/deploy_content_export.py", line 66, in send_export
    folder_list = recurse_folders(fid, folder_list, sdk, debug)
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_deployer/commands/deploy_content_export.py", line 48, in recurse_folders
    space = sdk.space(str(folder_id))
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_sdk/sdk/api31/methods.py", line 7076, in space
    transport_options=transport_options,
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_sdk/rtl/api_methods.py", line 152, in get
    return self._return(response, structure)
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_sdk/rtl/api_methods.py", line 101, in _return
    ret = self.deserialize(data=value, structure=structure)  # type: ignore
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/looker_sdk/rtl/serialize.py", line 79, in deserialize
    data, structure
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/cattr/converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/cattr/converters.py", line 314, in structure_attrs_fromdict
    dispatch(type_)(val, type_) if type_ is not None else val
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/cattr/converters.py", line 387, in _structure_union
    return self._structure_func.dispatch(other)(obj, other)
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/cattr/converters.py", line 327, in _structure_list
    for e in obj
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/cattr/converters.py", line 327, in <listcomp>
    for e in obj
  File "/Users/umair/.pyenv/versions/3.6.0/lib/python3.6/site-packages/cattr/converters.py", line 255, in _structure_default
    raise ValueError(msg)
```

**Comment by michaelcramer** [comment] 2022-01-06 00:49
@umairda is this still an issue you're able to reproduce?  If so, could you please respond with the Looker and python version you're using? Thanks!

**Comment by AdamMinton** [comment] 2022-03-24 01:27
Closing due to age.

**Closed by AdamMinton** 2022-03-24 01:27 UTC
Labels: question
